# Generated by Django 4.2 on 2023-05-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='quantidade_visitas',
            field=models.IntegerField(default=0),
        ),
    ]
